#
# ~/.bashrc
#

# If not running interactively, don't do anything


if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi


[[ $- != *i* ]] && return


PS1='[\u@\h \W]\$ '


powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/share/powerline/bindings/bash/powerline.sh

PATH=$PATH:~/platform-tools/
